server:
  port: 8000

spring:
  application:
    name: cambio-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Teste3345#
    url: jdbc:postgresql://localhost:5432/cambio_service

  flyway:
    url: jdbc:postgresql://localhost:5432/cambio_service
    user: postgres
    password: Teste3345#


